name: nour_task
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dartz:
  bloc:
  flutter_bloc:
  equatable:
  responsive_s:


flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: ubuntu
      fonts:
        - asset: assets/fonts/UbuntuCondensed-Regular.ttf




